apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    cekit.io/version: 3.6.0
    commit.image.appsody.dev/contextDir: /item-aggregator
    commit.image.appsody.dev/date: Tue Jun 16 23:39:32 2020 -0700
    commit.image.appsody.dev/message: scneario 3 rabbit mq
    commit.stack.appsody.dev/contextDir: /incubator/quarkus
    commit.stack.appsody.dev/date: Fri Jun 5 15:58:17 2020 +0100
    commit.stack.appsody.dev/message: Updated Quarkus stack to use Quarkus 1.5.0.Final
      (#827)
    graalvm-archive-filename: graalvm-ce-linux-amd64-19.3.1-java8.tar.gz
    graalvm-archive-url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
    graalvm-version: java8-19.3.1
    image.opencontainers.org/created: "2020-06-19T14:53:49-07:00"
    image.opencontainers.org/documentation: https://github.com/jbcodeforce/eda-kconnect-lab
    image.opencontainers.org/revision: 16398902137bea9eb363dbf95bf6f46101165ce7-modified
    image.opencontainers.org/source: https://github.com/jbcodeforce/eda-kconnect-lab/tree/master
    image.opencontainers.org/url: https://github.com/jbcodeforce/eda-kconnect-lab
    k8s.io/description: Quarkus.io builder image for building Quarkus applications.
    k8s.io/display-name: Centos + GraalVM + Maven Image
    maintainer: Quarkus Team <quarkus-dev@googlegroups.com>
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,java,quarkus
    org/label-schema.build-date: "20200504"
    org/label-schema.license: GPLv2
    org/label-schema.name: CentOS Base Image
    org/label-schema.schema-version: "1.0"
    org/label-schema.vendor: CentOS
    stack.appsody.dev/authors: Paul Robinson <paulrobinson>
    stack.appsody.dev/configured: docker.io/appsody/quarkus:0.4
    stack.appsody.dev/created: "2020-06-05T15:01:04Z"
    stack.appsody.dev/description: Quarkus runtime for running Java applications
    stack.appsody.dev/digest: sha256:ce7be9ae27524313662a2aac26d6482f37e8a037488fb3aaf85bbb33d507eee0
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/quarkus/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 03b26b6eb46603c07d6b6b2a7fef39e7417b9a31
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/quarkus/image
    stack.appsody.dev/tag: docker.io/appsody/quarkus:0.4.0
    stack.appsody.dev/title: Quarkus
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/quarkus
    stack.appsody.dev/vendor: CentOS
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: item-aggregator
    stack.appsody.dev/id: quarkus
    stack.appsody.dev/version: 0.4.0
  name: item-aggregator
  namespace: kconnect-lab
spec:
  applicationImage: ibmcase/item-aggregator
  createKnativeService: true
  expose: true
  monitoring:
    labels:
      k8s-app: item-aggregator
  service:
    port: 8080
    type: NodePort
  stack: quarkus
  env:
    - name: KAFKA_BROKERS
      valueFrom:
        configMapKeyRef:
          key: brokers
          name: kafka-brokers
    - name: KAFKA_USER
      valueFrom:
        configMapKeyRef:
          key: user
          name: kafka-brokers
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: user.password
          name: minimal-prod-ibm-es-kafka-user
    - name: KAFKA_CERT_PATH
      value: /deployments/certs/ca.p12
    - name: KAFKA_CERT_PWD
      valueFrom:
        secretKeyRef:
          key: ca.password
          name: minimal-prod-cluster-ca-cert
    - name: USER_CERT_PATH
      value: /deployments/certs/user.p12
    - name: USER_CERT_PWD
      valueFrom:
        secretKeyRef:
          key: user.password
          name: minimal-prod-ibm-es-kafka-user
  version: 1.0.0
  volumeMounts:
    - mountPath: /deployments/certs/ca.p12
      name: es-cert
      readOnly: true
      subPath: ca.p12
    - mountPath: /deployments/certs/user.p12
      name: user-cert
      readOnly: true
      subPath: user.p12
  volumes:
    - name: user-cert
      secret:
        secretName: minimal-prod-ibm-es-kafka-user
    - name: es-cert
      secret:
        secretName: minimal-prod-cluster-ca-cert
