version: '3'
services:
    zookeeper:
        image: strimzi/kafka:latest-kafka-2.5.0
        command: [
          "sh", "-c",
          "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
          - "2181:2181"
        environment:
          LOG_DIR: /tmp/logs
        networks:
          - kafka-network
      kafka:
        image: strimzi/kafka:latest-kafka-2.5.0
        command: [
          "sh", "-c",
          "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
        environment:
          LOG_DIR: "/tmp/logs"
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
          -  kafka-network
    kconnect:
        build: ../kconnect
        image: ibmcase/kconnect:1.0.0
        ports:
            - '8083:8083'
    ibmmq:
        image: ibmcom/mq
        ports:
            - '1414:1414'
            - '9443:9443'
            - '9157:9157'
        volumes:
            - qm1data:/mnt/mqm
        stdin_open: true
        tty: true
        restart: always
        environment:
            LICENSE: accept
            MQ_QMGR_NAME: QM1
            MQ_APP_PASSWORD: passw0rd
            MQ_ENABLE_METRICS: "true"
volumes:
    qm1data:
networks:
    kafka-network:
        name: kafkanet