version: '3'
services:
    # credentials guest:guest
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_DEFAULT_USER: rabbit-user
            RABBITMQ_DEFAULT_PASS: rabbit-pass
        volumes:
            - ./rabbitmq/enable_plugins:/etc/rabbitmq/enabled_plugins
    kconnect:
        hostname: kconnect
        image: ibmcase/kconlab:1.0.0
        ports:
            - '8083:8083'
    storeSaleGenerator:
        hostname: storeapp
        image: ibmcase/store-sale-producer:1.0.0
        ports:
            - '8080:8080'
networks:
    default:
        external:
            name: labnet