create sequence inventory_seq start with 1 increment by 2 NO CYCLE;
create sequence item_seq start with 1 increment by 2 NO CYCLE;
create sequence store_seq start with 1 increment by 2 NO CYCLE;
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL, 'SC01','Santa Clara','CA');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'SF01','San Francisco','CA');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'SF02','San Francisco','CA');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'PT01','Portland','OR');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'PT02','Portland','OR');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'SEA01','Seattle','WA');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'NYC01','New York','NY');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'NYC02','New York','NY');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'LA01','Los Angeles','CA');
INSERT INTO store(id, name, city, state) VALUES (store_seq.NEXTVAL,'LA02','Los Angeles','CA');
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT01','Dune Frank Herbert',20);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT02','The Hobbit Tolkien',30);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT03','Gloomhaven',140);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT04','Pandemic Legacy: Season 1',72);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT05','Terraforming Mars',42);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT06','Brass: Birmingham',155);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT07','Gaia Project',80);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT08','Arkham Horror: The Card Game',32);
INSERT INTO item(id,code,title,price) VALUES(item_seq.NEXTVAL,'IT09','Viticulture Essential Edition',46);
